name=LightConnect
version=1.0.1
author=Otto <den-life@mail.ru>
maintainer=Otto <den-life@mail.ru>
sentence=Modern and lightweight WiFi Manager Portal for ESP8266 and ESP32.
paragraph=Beautiful captive portal for initial WiFi setup. Supports scanning available networks, selecting SSID, entering WiFi password and optional web-interface login and password. Works in Arduino IDE 1 and 2.
category=Communication
url=https://github.com/Otto17/LightConnect
architectures=esp8266, esp32
